BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "All_Ingredients" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Main" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL UNIQUE,
	"Ingredients"	NUMERIC NOT NULL UNIQUE,
	"Steps"	NUMERIC NOT NULL UNIQUE,
	FOREIGN KEY("Steps") REFERENCES "Recipe_Steps",
	FOREIGN KEY("Ingredients") REFERENCES "Recipe_Ingredients",
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Recipe_Ingredients" (
	"ID"	NUMERIC NOT NULL,
	"Name"	TEXT NOT NULL,
	"Amount"	INTEGER NOT NULL,
	"Unit"	TEXT NOT NULL,
	"Key"	NUMERIC NOT NULL,
	FOREIGN KEY("Key") REFERENCES "Main"("ID"),
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "Recipe_Steps" (
	"ID"	NUMERIC NOT NULL,
	"Name"	TEXT NOT NULL,
	PRIMARY KEY("ID")
);
COMMIT;
